### PR TITLE
MonadIO instance

### PR DESCRIPTION
**Pull request by greydot**
This adds somehow forgotten MonadIO instance for Lifted. Also some INLINE pragmas thrown in, though GHC should inline those functions in most cases anyway.

### CODE REVIEW

**Comment by suhailshergill** [comment]
@greydot could you change the target to `develop` please? thanks!
i'll make `develop` the default branch which will help with future PRs

**Comment by greydot** [comment]
I forgot that, yeah. Done.

**Comment by greydot** [comment]
Do you need tests for this instance? It's basically the same as MonadBase IO, but with one parameter hardcoded.

**Comment by suhailshergill** [comment]
nope, this seems straightforward enough

**Pull request merged**
