### PR TITLE
Use haskell-stack

### PR DESCRIPTION
**Pull request by aiya000**
Why haskell-stack is not used ? 🤔

### CODE REVIEW

**Comment by suhailshergill** [comment]
@aiya000 thanks for the PR!
what's the mechanism in `haskell-stack` to switch between GHC versions? specifically, i would like to support each of the GHC versions listed in the cabal file: https://github.com/suhailshergill/extensible-effects/blob/develop/extensible-effects.cabal#L46

**Comment by aiya000** [comment]
@suhailshergill Thanks, I understood it 😄  

It can be with switching a resolver version of stack.yaml 👍  
GHC versions is determined by it.

e.g.
if I create `ghc-7.10.yaml`

```yaml
resolver: lts-6.19
packages:
  - '.'
extra-deps: []
flags: {}
extra-package-dbs: []
```

and I run

```console
$ STACK_YAML=ghc-7.10.yaml stack test
```

the test is ran with ghc-7.10 !

- - -

## Reference

- [lts-6.19](https://www.stackage.org/lts-6.19)
- [lts-7.24](https://www.stackage.org/lts-7.24)

- - -

I can organize about this if you allow it to me :dog2:

**Comment by suhailshergill** [comment]
@aiya000 i see. i imagine we'd need:
- a different file for each supported GHC version
- a default file for the latest GHC version

correct?

please push the changes and i'll review

**Comment by aiya000** [comment]
@suhailshergill Yes, it is.

But a default file (stack.yaml) needs manually update for its resolver, if we need to use latest GHC.

Is it problem ? 😢

**Comment by suhailshergill** [comment]
@aiya000 no that makes sense. by "latest" i meant latest as of now.

**Comment by aiya000** [comment]
@suhailshergill mmm... I think I cannot do it without stack.yaml updating...  
Thank you 😄

**Comment by suhailshergill** [comment]
@aiya000 i think that's ok. i think it would be ok to have multiple such yaml files. there's already something like this today (see https://github.com/suhailshergill/extensible-effects/blob/develop/shell.nix , https://github.com/suhailshergill/extensible-effects/blob/develop/shell-7.6.3.nix, https://github.com/suhailshergill/extensible-effects/blob/develop/shell-7.8.4.nix, and https://github.com/suhailshergill/extensible-effects/blob/develop/shell-7.10.1.nix)

i imagine the haskell-stack yaml files to replace those, correct?

**Comment by aiya000** [comment]
:smile:

Sorry, I don't know what is .nix :bow:  
What is it?

**Comment by aiya000** [comment]
I think `.nix` files allows that NixOS distribution installs `extensible-effects` package.  
And `.nix` files are generated by `cabal2nix` in `Makefile`.

Also we need alternate `Makefile` and `cabal2nix` (like `stack2nix`) (and maybe `.travis.yml`) by `haskell-stack`.  
Is this OK ? 🤔

**Comment by aiya000** [comment]
PS.
I confirmed stack.yaml of *latest* ghc can be generated by

```console
$ stack config set resolver nightly
$ git diff
diff --git a/stack.yaml b/stack.yaml
index c7d5d8a..634a356 100644
--- a/stack.yaml
+++ b/stack.yaml
@@ -1,6 +1,6 @@
-resolver: lts-7.24
-packages:
-  - '.'
-extra-deps: []
 flags: {}
 extra-package-dbs: []
+packages:
+- '.'
+extra-deps: []
+resolver: nightly-2017-07-14
```

👍 

It updates stack.yaml's `resolver`.

**Pull request closed without merging**
