### PR TITLE
Add member list operator

### PR DESCRIPTION
**Pull request by greydot**
This PR add (::>) type level operator to reduce boilerplate in function constraints.

For example, [E1, E2] ::> r is expanded to (Member E1 r, Member E2 r).

As always, the name could be better, so I'm open to suggestions in this case.

### CODE REVIEW

**Comment by suhailshergill** [comment]
@greydot how about `<=` (unsure if syntactically valid) or `<::` instead?  I something which resembles subset operator

**Comment by greydot** [comment]
`<=` doesn't work because it's an Ord function. I'll change it to `<::`.

**Comment by greydot** [comment]
Do you want me to bump version in both pull requests?

**Comment by suhailshergill** [comment]
@greydot yes either that or you could change target of both to develop. And then we could have a singe version bump as we go from develop to master.

**Comment by greydot** [comment]
Actually, (<::) doesn't work either. This code
```{-# LANGUAGE DataKinds, TypeOperators, TypeFamilies, MultiParamTypeClasses #-}
module Infix (M, (<::)) where

import Data.Kind

class M (m :: * -> *) r

type family (<::) (ms :: [* -> *]) r where
  (<::) '[] r = (() :: Constraint)
  (<::) (m ': ms) r = (M m r, (<::) ms r)
```
fails to build with the following: `infix.hs:2:18: error: Not in scope: ‘<::’`

The code with (::>) builds just fine. I guess I'll try to investigate this further.

Meahwhile, (:<=) could work. What do you think?

**Pull request merged**
