### PR TITLE
Implement Operational Monad

### PR DESCRIPTION
**Pull request by solorab**

### CODE REVIEW

**Comment by solorab** [comment]
This pull request is dead for a long time. So I want to close this. Thank you.

**Comment by suhailshergill** [comment]
@solorab apologies for dropping the ball on this. life intervened and this slipped my notice.

the main thing stopping me at this point from going ahead with merging this patch are 
- the lack of tests associated with expected behaviour etc. 
- referencing/linking to the operational package/paper from the code comments

if you could make the above changes i can merge it in. alternatively, i'll make the changes myself and add those in.

again, my apologies for having starved this pull request of attention

**Comment by suhailshergill** [comment]
@solorab taking ownership of merging this patchset to the best of my abilities. doing this as part of #43

**Comment by solorab** [comment]
I am sorry that I didn't notice your comment and made you fix my pull request.
Thank you for fixing and merging.

**Comment by suhailshergill** [comment]
@solorab no worries, we're all good :)

**Pull request closed without merging**
