### PR TITLE
feature/nat: define handlers via natural transform

### PR DESCRIPTION
**Pull request by suhailshergill**
@greydot since you've been working on #99 , I decided not to merge these into `#develop` directly. Please review this PR and merge per your convenience.
This changeset makes a non-breaking API addition.

### CODE REVIEW

**Comment by greydot** [comment]
Oh... This is actually neat. I'll check this more thoroughly tomorrow. Meanwhile could you squash these two commits into one?

**Comment by greydot** [comment]
On a related subject. Maybe we should develop a more consistent naming scheme? This mix of snake_case and camelCase is a bit ugly imo.

**Comment by suhailshergill** [comment]
> On a related subject. Maybe we should develop a more consistent naming scheme? This mix of snake_case and camelCase is a bit ugly imo.

agreed. let me make the changes self-consistent for now at least.

**Comment by suhailshergill** [comment]
> Meanwhile could you squash these two commits into one?

done, cheers

**Review by greydot — APPROVED** [review]
This is good.

Other than `mapMdebug` not being tail-recursive, which I'd guess doesn't matter here, I see no problems here. When do you plan releasing this on hackage? My package log-effect could use handle_nat'.

**Comment by suhailshergill** [comment]
> Other than `mapMdebug` not being tail-recursive, which I'd guess doesn't matter here

Given that it's a test, and hasn't caused any issues, I agree.

> When do you plan releasing this on hackage? My package log-effect could use handle_nat'.

I was thinking it would be a good idea for you to carry out the release; perhaps after we make a decision wrt `Control.Eff.Example.Fresh` and `Control.Eff.Extend.Tutorial`. Thoughts?

**Comment by greydot** [comment]
Alright then. I'll try to finish the tutorial by the end of this week and probably merge those two modules. Two examples is better than one.

**Pull request merged**
